#!/bin/bash

dir=`pwd`


if [[ `diff /mnt/hgfs/shared/rep2/OShw2/entry.S /usr/src/linux-2.4.18-14custom/arch/i386/kernel/entry.S` != "" ]]; then
	cp /mnt/hgfs/shared/rep2/OShw2/entry.S /usr/src/linux-2.4.18-14custom/arch/i386/kernel/
fi
if [[ `diff /mnt/hgfs/shared/rep2/OShw2/exit.c /usr/src/linux-2.4.18-14custom/kernel/exit.c` != "" ]]; then
	cp /mnt/hgfs/shared/rep2/OShw2/exit.c /usr/src/linux-2.4.18-14custom/kernel/
fi
if [[ `diff /mnt/hgfs/shared/rep2/OShw2/fork.c /usr/src/linux-2.4.18-14custom/kernel/fork.c` != "" ]]; then
	cp /mnt/hgfs/shared/rep2/OShw2/fork.c /usr/src/linux-2.4.18-14custom/kernel/
fi

if [[ `diff /mnt/hgfs/shared/rep2/OShw2/sched.c /usr/src/linux-2.4.18-14custom/kernel/sched.c` != "" ]]; then
	cp /mnt/hgfs/shared/rep2/OShw2/sched.c /usr/src/linux-2.4.18-14custom/kernel/
fi

if [[ `diff /mnt/hgfs/shared/rep2/OShw2/sched.h /usr/src/linux-2.4.18-14custom/include/linux/sched.h` != "" ]]; then
	cp /mnt/hgfs/shared/rep2/OShw2/sched.h /usr/src/linux-2.4.18-14custom/include/linux/
fi

if [[ `diff /mnt/hgfs/shared/rep2/OShw2/syscall.h  /usr/src/linux-2.4.18-14custom/include/linux/syscall.h` != "" ]]; then
	cp /mnt/hgfs/shared/rep2/OShw2/syscall.h  /usr/src/linux-2.4.18-14custom/include/linux/
fi

if [[ `diff /mnt/hgfs/shared/rep2/OShw2/unistd.h  /usr/src/linux-2.4.18-14custom/include/asm/unistd.h` != "" ]]; then
	cp /mnt/hgfs/shared/rep2/OShw2/unistd.h  /usr/src/linux-2.4.18-14custom/include/asm/
fi


cd /usr/src/linux-2.4.18-14custom
make bzImage
cd arch/i386/boot
cp bzImage /boot/vmlinuz-2.4.18-14custom

cd $dir
unset dir
echo "--DONE--"
