#!/bin/bash

dir=`pwd`

cp /mnt/hgfs/shared/rep2/OShw2/entry.S /usr/src/linux-2.4.18-14custom/arch/i386/kernel/
cp /mnt/hgfs/shared/rep2/OShw2/exit.c /usr/src/linux-2.4.18-14custom/kernel/
cp /mnt/hgfs/shared/rep2/OShw2/fork.c /usr/src/linux-2.4.18-14custom/kernel/
cp /mnt/hgfs/shared/rep2/OShw2/sched.c /usr/src/linux-2.4.18-14custom/kernel/
cp /mnt/hgfs/shared/rep2/OShw2/sched.h /usr/src/linux-2.4.18-14custom/include/linux/
cp /mnt/hgfs/shared/rep2/OShw2/syscall.h  /usr/src/linux-2.4.18-14custom/include/linux/
cp /mnt/hgfs/shared/rep2/OShw2/unistd.h  /usr/src/linux-2.4.18-14custom/include/asm/



cd /usr/src/linux-2.4.18-14custom
make bzImage
cd arch/i386/boot
cp bzImage /boot/vmlinuz-2.4.18-14custom

cd $dir
unset dir
echo "--DONE--"